## CI pipeline will be started on every branch
# Pipeline requires the folowing pipeline variables:

  trigger:
    batch: true
    branches:
      include:    
      - main
      - feature/*
    paths:
      include:
        - eps02_DevOpsAZContainerAppsBoomi/*
  pr: none
  
  variables:
    - group: boomi-dev 
  
  # Use build definition name for build/release numbers
  name: $(BuildDefinitionName).$(Year:yy)$(DayOfYear)$(rev:.r)
  
  # Call the build process template
  stages:
  - stage: Build
  
    jobs:
      - template: stages/build-stage-bicep.yml
        parameters:
          artifacts:
            - name: bicep-artifact
              templateDirectory: eps02_DevOpsAZContainerAppsBoomi/infra
          azureSubscription: $(AZURESERVICECONNECTION)
          bicep:
            templateFile: eps02_DevOpsAZContainerAppsBoomi/infra/main.bicep
          pool:
            name: 'Azure Pipelines'
  
  - stage: Development 
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
    - group: boomi-dev
    jobs:
    - template: stages/release-stage-bicep.yml
      parameters:
        name: 'BicepDeploy'
        azureSubscription:  $(AZURESERVICECONNECTION)
        bicep: 
          artifactName: bicep-artifact
          parametersFile: $(BICEPPARAMETERFILE)
          location: $(AZURERESOURCEREGION)
          templateFile: main.bicep
        devOpsEnvironment: Development
        pool:
          name: 'Azure Pipelines'
          
  - stage: Production 
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
    - group: boomi-prod
    jobs:
    - template: stages/release-stage-bicep.yml
      parameters:
        name: 'BicepDeploy'
        azureSubscription:  $(AZURESERVICECONNECTION)
        bicep: 
          artifactName: bicep-artifact
          parametersFile: $(BICEPPARAMETERFILE)
          location: $(AZURERESOURCEREGION)
          templateFile: main.bicep
        devOpsEnvironment: Production
        pool:
          name: 'Azure Pipelines'
  