jobs:
- job: buildAndVerifyBicep
  displayName: Build/Verification
  continueOnError: false
  pool: ${{parameters.pool}}
  workspace:
    clean: all

  steps:
    # Build Bicep file
    - task: AzureCLI@2
      displayName: Azure CLI Bicep Build
      inputs:
        scriptType: "bash"
        scriptLocation: inlineScript
        inlineScript: |
          az bicep build -f ${{parameters.bicep.templateFile}}

    # Publish Bicep file into Azure DevOps artifacts
    - ${{ each artifact in parameters.artifacts }}:
        - publish: ${{artifact.templateDirectory}}
          displayName: Publish Artifacts ${{artifact.name}}
          artifact: ${{artifact.name}}
