jobs:
  - deployment: ${{parameters.name}}  
    environment: ${{parameters.devOpsEnvironment}}
    continueOnError: false
    dependsOn: ${{parameters.dependsOn}} 
    condition: ${{parameters.condition}} 
    pool: ${{ parameters.pool }}
    workspace:
      clean: all

    strategy: 
      runOnce:
        deploy:
          steps:     
            - task: AzureCLI@2
              displayName: Azure CLI Bicep Release
              inputs:
                azureSubscription: ${{parameters.azureSubscription}}
                scriptType: "bash"
                scriptLocation: inlineScript
                inlineScript: |
                 echo "Deploying Bicep template with dynamic parameters and static parameter file..."
                  az deployment sub create \
                    --name ${{ parameters.name }} \
                    --location $(AZURERESOURCEREGION) \  # Dynamic from boomi-dev
                    --template-file $(Pipeline.Workspace)/${{ parameters.bicep.artifactName }}/${{ parameters.bicep.templateFile }} \
                    --parameters @$(Pipeline.Workspace)/${{ parameters.bicep.artifactName }}/$(BICEPPARAMETERFILE) \ 
                    --parameters \
                      location=$(AZURERESOURCEREGION) \
                      subscriptionId=$(SUBSCRIPTIONID) \
                      boomiAccountId=$(BOOMIACCOUNTID) \
                      boomiAtomName=$(BOOMIATOMNAME) \
                      boomiAtomOrMolecule=$(BOOMIATOMORMOLECULE) \
                      boomiContainerVersion=$(BOOMICONTAINERVERSION) \
                      boomiEnvironmentClassification=$(BOOMIENVIRONMENTCLASSIFICATION) \
                      boomiEnvironmentId=$(BOOMIENVIRONMENTID) \
                      boomiEnvironmentName=$(BOOMIENVIRONMENTNAME)\
                      boomiInstallerToken=$(BOOMIINSTALLERTOKEN)

